version: '3'
services:
  sales_data_pipeline:
    build: .
    environment:
      - OPENWEATHERMAP_API_KEY=5b6c8ec3280127b16da26dfb1a707490
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_database
    ports:
      - "5432:5432"
